Repository AY2223S1-CS2103T-W12-3/tp, pull requests merged in 2022-11, with the labels that each got.

#257 Update to UG & DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CommandDiagram.puml
  docs/diagrams/CommandHistoryActivityDiagram.puml
  docs/diagrams/CommandHistoryClassDiagram.puml
  docs/diagrams/ComponentManagers.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/plantuml/ColorCoding.puml
  docs/images/ColorCoding.png
  docs/images/CommandDiagram.png
  docs/images/CommandHistoryActivityDiagram-0.png
  docs/images/CommandHistoryClassDiagram-0.png
  docs/images/ComponentManagers.png
  docs/images/LatestModelClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UiClassDiagram2.png
  docs/images/ug-photos/current_data_folder_footer.png
  docs/index.md
  docs/team/nealetham.md
  docs/ug-pages/authors.md
  docs/ug-pages/command-summary.md
  docs/ug-pages/data-management.md
  docs/ug-pages/exiting-the-program.md
  docs/ug-pages/faq.md
  docs/ug-pages/file-management.md
  docs/ug-pages/getting-help.md
  docs/ug-pages/glossary.md
  docs/ug-pages/modifying-residents.md
  docs/ug-pages/quality-of-life.md
  docs/ug-pages/upcoming-features.md
  docs/ug-pages/venue-booking.md
  docs/ug-pages/viewing-residents.md
  src/main/java/seedu/rc4hdb/ui/BookingTableView.java
Labels: type.Documentation, type.Chore

#270 Remove list /i and /e feature
  src/main/java/seedu/rc4hdb/logic/commands/residentcommands/ListCommand.java
  src/main/java/seedu/rc4hdb/logic/parser/Rc4hdbParser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/ColumnManipulatorCommandParser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/ListCommandParser.java
  src/test/java/seedu/rc4hdb/logic/parser/Rc4hdbParserTest.java
  src/test/java/seedu/rc4hdb/logic/parser/commandparsers/ListCommandParserTest.java
Labels: priority.Moderate

#268 Update individual PPP for week 12
  docs/team/nealetham.md
  docs/team/nseah21.md
Labels: type.Documentation

#196 Add unit tests for Model classes
  src/main/java/seedu/rc4hdb/model/venues/DailySchedule.java
  src/main/java/seedu/rc4hdb/model/venues/Venue.java
  src/main/java/seedu/rc4hdb/model/venues/booking/Booking.java
  src/main/java/seedu/rc4hdb/model/venues/booking/BookingDescriptor.java
  src/test/java/seedu/rc4hdb/model/venues/DailyScheduleTest.java
  src/test/java/seedu/rc4hdb/model/venues/UniqueVenueListTest.java
  src/test/java/seedu/rc4hdb/model/venues/VenueBookTest.java
  src/test/java/seedu/rc4hdb/model/venues/VenueTest.java
  src/test/java/seedu/rc4hdb/model/venues/booking/RecurrentBookingTest.java
  src/test/java/seedu/rc4hdb/storage/venue/JsonAdaptedVenueTest.java
  src/test/java/seedu/rc4hdb/testutil/TypicalBookings.java
  src/test/java/seedu/rc4hdb/testutil/TypicalVenues.java
  src/test/java/seedu/rc4hdb/testutil/VenueBuilder.java
Labels: priority.Moderate

#275 `BUG FIX`: Venue bar not updating
  src/main/java/seedu/rc4hdb/model/ModelManager.java
Labels: type.Bug, type.Chore, severity.Medium

#271 Fix VenueListView width, unintended selection of VenueCard
  src/main/java/seedu/rc4hdb/ui/CommandBox.java
  src/main/java/seedu/rc4hdb/ui/NoSelectionModel.java
  src/main/java/seedu/rc4hdb/ui/VenueListView.java
  src/main/java/seedu/rc4hdb/ui/history/BackwardHistory.java
  src/main/java/seedu/rc4hdb/ui/history/ForwardHistory.java
  src/test/java/seedu/rc4hdb/ui/CommandHistoryTest.java
Labels: priority.High

#276 Fix storage test causing creation of folder
  src/test/java/seedu/rc4hdb/storage/DataStorageManagerTest.java
  src/test/java/seedu/rc4hdb/storage/StorageManagerTest.java
Labels: priority.High

#273 Add DG acknowledgement for cleanBom method in CsvReader
  docs/DeveloperGuide.md
Labels: type.Documentation

#277 `REVAMP` UI and Model classes
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  src/main/java/seedu/rc4hdb/logic/Logic.java
  src/main/java/seedu/rc4hdb/logic/LogicManager.java
  src/main/java/seedu/rc4hdb/logic/commands/venuecommands/BookCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/venuecommands/UnbookCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/venuecommands/VenueDeleteCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/venuecommands/VenueViewCommand.java
  src/main/java/seedu/rc4hdb/model/Model.java
  src/main/java/seedu/rc4hdb/model/ModelManager.java
  src/main/java/seedu/rc4hdb/model/VenueBook.java
  src/main/java/seedu/rc4hdb/model/venues/UniqueVenueList.java
  src/main/java/seedu/rc4hdb/model/venues/Venue.java
  src/main/java/seedu/rc4hdb/storage/venuebook/JsonAdaptedVenue.java
  src/main/java/seedu/rc4hdb/ui/BookingTableView.java
  src/main/java/seedu/rc4hdb/ui/CurrentWorkingFileFooter.java
  src/main/java/seedu/rc4hdb/ui/MainWindow.java
  src/main/java/seedu/rc4hdb/ui/ResidentTableView.java
  src/main/java/seedu/rc4hdb/ui/VenueListView.java
  src/main/java/seedu/rc4hdb/ui/VenueTabView.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/rc4hdb/model/ModelStub.java
  src/test/java/seedu/rc4hdb/model/venues/UniqueVenueListTest.java
  src/test/java/seedu/rc4hdb/model/venues/VenueTest.java
  src/test/java/seedu/rc4hdb/testutil/VenueBuilder.java
Labels: type.Bug, type.Chore, severity.VeryLow

#287 `BUG FIX` Booking table not updating when switching files
  src/main/java/seedu/rc4hdb/model/ModelManager.java
  src/main/java/seedu/rc4hdb/ui/BookingTableView.java
Labels: type.Bug, type.Chore, severity.High

#290 `BUG FIX` Empty venue list appears white
  src/main/resources/view/VenueListView.fxml
Labels: type.Bug, type.Chore, severity.VeryLow

#278 `BUG FIX` Command bugs
  src/main/java/seedu/rc4hdb/commons/core/Messages.java
  src/main/java/seedu/rc4hdb/logic/commands/misccommands/ExitCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/residentcommands/AddCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/residentcommands/DeleteCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/residentcommands/EditCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/residentcommands/FilterCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/residentcommands/FindCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/residentcommands/RemoveCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/venuecommands/BookCommand.java
  src/main/java/seedu/rc4hdb/model/resident/fields/Gender.java
  src/main/java/seedu/rc4hdb/model/resident/fields/House.java
  src/main/java/seedu/rc4hdb/model/resident/fields/MatricNumber.java
  src/main/java/seedu/rc4hdb/model/resident/fields/Room.java
  src/test/java/seedu/rc4hdb/logic/commands/ModelCommandTestUtil.java
  src/test/java/seedu/rc4hdb/logic/commands/residentcommands/DeleteCommandTest.java
  src/test/java/seedu/rc4hdb/logic/commands/residentcommands/EditCommandTest.java
  src/test/java/seedu/rc4hdb/model/resident/fields/GenderTest.java
  src/test/java/seedu/rc4hdb/model/resident/fields/HouseTest.java
  src/test/java/seedu/rc4hdb/model/resident/fields/MatricNumberTest.java
  src/test/java/seedu/rc4hdb/model/resident/fields/RoomTest.java
  src/test/java/seedu/rc4hdb/storage/residentbook/JsonAdaptedResidentTest.java
Labels: type.Bug, severity.Medium

#280 `BUG FIX` Update User Guide bugs
  docs/UserGuide.md
  docs/team/nareus.md
Labels: type.Bug, severity.Low

#298 `TESTS` ModelManager
  src/test/java/seedu/rc4hdb/model/ModelManagerTest.java
  src/test/java/seedu/rc4hdb/model/venues/UniqueVenueListTest.java
  src/test/java/seedu/rc4hdb/testutil/TypicalBookings.java
  src/test/java/seedu/rc4hdb/testutil/TypicalVenues.java
  src/test/java/seedu/rc4hdb/testutil/VenueBookBuilder.java
Labels: type.Chore

#279 `BUG FIX` Alvin code fix
  src/main/java/seedu/rc4hdb/model/resident/Resident.java
  src/main/java/seedu/rc4hdb/model/venues/booking/fields/Hour.java
  src/main/java/seedu/rc4hdb/model/venues/booking/fields/HourPeriod.java
Labels: type.Bug, type.Chore

#299 `BUG FIX` Resident uniqueness not tied to email, phone, matric number, room
  docs/UserGuide.md
  src/main/java/seedu/rc4hdb/model/StringField.java
  src/main/java/seedu/rc4hdb/model/resident/Resident.java
  src/main/java/seedu/rc4hdb/model/util/SampleDataUtil.java
  src/test/java/seedu/rc4hdb/model/resident/ResidentTest.java
  src/test/java/seedu/rc4hdb/model/resident/fields/EmailTest.java
Labels: type.Bug, type.Documentation, type.Chore, severity.Medium

#272 `BUG FIX`: Import command not detecting duplicate residents
  docs/UserGuide.md
  src/main/java/seedu/rc4hdb/logic/commands/filecommands/ImportCommand.java
  src/main/java/seedu/rc4hdb/storage/DataStorageManager.java
  src/test/java/seedu/rc4hdb/logic/commands/filecommands/ImportCommandTest.java
Labels: type.Bug, type.Chore, severity.Medium

#309 Update DG and PPP
  docs/DeveloperGuide.md
  docs/diagrams/AbstractClassesForShowHideFeature.puml
  docs/diagrams/MainWindowRelationships.puml
  docs/diagrams/ManipulatingColumnsActivityDiagram.puml
  docs/diagrams/ModelClassDiagramWithoutVenueBooking.puml
  docs/images/AbstractClassesForShowHideFeature.png
  docs/images/BetterModelClassDiagram.png
  docs/images/ManipulatingColumnsActivityDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ModelClassDiagramWithoutVenueBooking.png
  docs/images/UpdatedBetterModelClassDiagram.png
  docs/team/nseah21.md
Labels: type.Documentation

#303 `CLEANUP` Remove all references to Parser
  src/main/java/seedu/rc4hdb/logic/parser/Parser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/AddCommandParser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/BookCommandParser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/ColumnManipulatorCommandParser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/CommandParser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/DeleteCommandParser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/EditCommandParser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/FilterCommandParser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/FindCommandParser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/RemoveCommandParser.java
  src/test/java/seedu/rc4hdb/logic/parser/commandparsers/CommandParserTestUtil.java
Labels: type.Chore

#294 `TESTS` Implement Venue Logic Tests
  src/main/java/seedu/rc4hdb/logic/commands/venuecommands/BookCommand.java
  src/test/java/seedu/rc4hdb/logic/commands/ModelCommandTestUtil.java
  src/test/java/seedu/rc4hdb/logic/commands/venuecommands/BookCommandTest.java
  src/test/java/seedu/rc4hdb/logic/commands/venuecommands/VenueAddCommandTest.java
  src/test/java/seedu/rc4hdb/logic/commands/venuecommands/VenueDeleteCommandTest.java
  src/test/java/seedu/rc4hdb/testutil/BookingBuilder.java
  src/test/java/seedu/rc4hdb/testutil/BookingDescriptorBuilder.java
  src/test/java/seedu/rc4hdb/testutil/TypicalBookings.java
Labels: type.Chore

#292 Update code to be defensive
  src/main/java/seedu/rc4hdb/logic/LogicManager.java
  src/main/java/seedu/rc4hdb/logic/commands/residentcommands/ColumnManipulatorCommand.java
  src/main/java/seedu/rc4hdb/model/Model.java
  src/main/java/seedu/rc4hdb/model/ModelManager.java
  src/main/java/seedu/rc4hdb/model/venues/Venue.java
  src/main/java/seedu/rc4hdb/storage/venuebook/JsonAdaptedVenue.java
  src/main/java/seedu/rc4hdb/ui/BookingTableView.java
  src/test/java/seedu/rc4hdb/model/ModelStub.java
  src/test/java/seedu/rc4hdb/model/venues/UniqueVenueListTest.java
  src/test/java/seedu/rc4hdb/model/venues/VenueTest.java
  src/test/java/seedu/rc4hdb/testutil/VenueBuilder.java
Labels: type.Chore

#314 Photo update for UG
  docs/UserGuide.md
  docs/images/ug-photos/booking_photo.png
  docs/images/ug-photos/current_data_folder_footer.png
  docs/images/ug-photos/filter_command.png
  docs/images/ug-photos/filter_command_2.png
  docs/images/ug-photos/find_command.png
  docs/images/ug-photos/find_photo.png
  docs/images/ug-photos/hideonly_command.png
  docs/images/ug-photos/hideonly_photo.png
  docs/images/ug-photos/list_command.png
  docs/images/ug-photos/list_i_list_e_command.png
  docs/images/ug-photos/list_photo.png
  docs/images/ug-photos/showonly_command.png
  docs/images/ug-photos/showonly_photo.png
Labels: type.Documentation

#313 Improve code quality
  src/main/java/seedu/rc4hdb/logic/commands/residentcommands/ColumnManipulatorCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/residentcommands/ListCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/residentcommands/ResetCommand.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/ColumnManipulatorCommandParser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/CommandParser.java
  src/main/java/seedu/rc4hdb/model/resident/fields/Gender.java
  src/main/java/seedu/rc4hdb/model/resident/fields/House.java
  src/main/java/seedu/rc4hdb/model/resident/fields/MatricNumber.java
  src/main/java/seedu/rc4hdb/model/resident/fields/Name.java
  src/main/java/seedu/rc4hdb/model/resident/fields/Phone.java
  src/main/java/seedu/rc4hdb/model/resident/fields/Room.java
  src/main/java/seedu/rc4hdb/model/venues/Venue.java
  src/main/java/seedu/rc4hdb/ui/ResidentTableView.java
  src/test/java/seedu/rc4hdb/logic/commands/residentcommands/ListCommandTest.java
Labels: type.CodeQuality

#316 Update DG and PPP
  docs/UserGuide.md
  docs/team/nseah21.md
Labels: type.Documentation

#312 Standardize format across UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/img.png
  docs/team/nealetham.md
Labels: type.Documentation

#319 Update DG and PPP
  docs/DeveloperGuide.md
  docs/team/nseah21.md
Labels: type.Documentation
