Repository AY2223S1-CS2103T-W12-3/tp, pull requests merged in 2022-10, with the labels that each got.

#31 Add support for find command (from AB3) to perform substring search
  src/main/java/seedu/rc4hdb/commons/util/StringUtil.java
  src/test/java/seedu/rc4hdb/commons/util/StringUtilTest.java
Labels: type.Story, priority.Moderate

#55 Update Use Cases and DG Format
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#59 Add command to filter residents by specific fields
  src/main/java/seedu/rc4hdb/logic/commands/modelcommands/FilterCommand.java
  src/main/java/seedu/rc4hdb/logic/parser/AddressBookParser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/FilterCommandParser.java
  src/main/java/seedu/rc4hdb/model/ModelManager.java
  src/main/java/seedu/rc4hdb/model/person/AttributesMatchKeywordsPredicate.java
Labels: type.Story, priority.High

#70 Customize model with RC4 resident fields
  src/main/java/seedu/rc4hdb/logic/commands/modelcommands/EditCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/modelcommands/FilterCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/modelcommands/FindCommand.java
  src/main/java/seedu/rc4hdb/logic/parser/ParserUtil.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/AddCommandParser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/FindCommandParser.java
  src/main/java/seedu/rc4hdb/model/person/Person.java
  src/main/java/seedu/rc4hdb/model/person/predicates/AttributesMatchKeywordsPredicate.java
  src/main/java/seedu/rc4hdb/model/person/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/rc4hdb/model/resident/Email.java
  src/main/java/seedu/rc4hdb/model/resident/Gender.java
  src/main/java/seedu/rc4hdb/model/resident/House.java
  src/main/java/seedu/rc4hdb/model/resident/MatricNumber.java
  src/main/java/seedu/rc4hdb/model/resident/Name.java
  src/main/java/seedu/rc4hdb/model/resident/Phone.java
  src/main/java/seedu/rc4hdb/model/resident/Resident.java
  src/main/java/seedu/rc4hdb/model/resident/Room.java
  src/main/java/seedu/rc4hdb/model/util/SampleDataUtil.java
  src/main/java/seedu/rc4hdb/storage/JsonAdaptedPerson.java
  src/test/java/seedu/rc4hdb/logic/commands/modelcommands/FindCommandTest.java
  src/test/java/seedu/rc4hdb/logic/commands/modelcommands/ModelCommandTestUtil.java
  src/test/java/seedu/rc4hdb/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/rc4hdb/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/rc4hdb/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/rc4hdb/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/rc4hdb/logic/parser/ParserUtilTest.java
  src/test/java/seedu/rc4hdb/model/ModelManagerTest.java
  src/test/java/seedu/rc4hdb/model/person/EmailTest.java
  src/test/java/seedu/rc4hdb/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/rc4hdb/model/person/NameTest.java
  src/test/java/seedu/rc4hdb/model/person/PhoneTest.java
  src/test/java/seedu/rc4hdb/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/rc4hdb/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/rc4hdb/testutil/PersonBuilder.java
Labels: type.Story, priority.High

#75 Minor GUI updates
  src/main/java/seedu/rc4hdb/ui/PersonTableView.java
  src/main/java/seedu/rc4hdb/ui/UiManager.java
  src/main/resources/images/RC4HDB.png
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#74 Edit Commands Test
  src/main/java/seedu/rc4hdb/logic/LogicManager.java
  src/main/java/seedu/rc4hdb/logic/parser/ResidentBookParser.java
  src/test/java/seedu/rc4hdb/logic/LogicManagerTest.java
  src/test/java/seedu/rc4hdb/logic/commands/modelcommands/AddCommandIntegrationTest.java
  src/test/java/seedu/rc4hdb/logic/commands/modelcommands/AddCommandTest.java
  src/test/java/seedu/rc4hdb/logic/commands/modelcommands/ClearCommandTest.java
  src/test/java/seedu/rc4hdb/logic/commands/modelcommands/DeleteCommandTest.java
  src/test/java/seedu/rc4hdb/logic/commands/modelcommands/EditCommandTest.java
  src/test/java/seedu/rc4hdb/logic/commands/modelcommands/EditPersonDescriptorTest.java
  src/test/java/seedu/rc4hdb/logic/commands/modelcommands/FindCommandTest.java
  src/test/java/seedu/rc4hdb/logic/commands/modelcommands/ListCommandTest.java
  src/test/java/seedu/rc4hdb/logic/commands/modelcommands/ModelCommandTestUtil.java
  src/test/java/seedu/rc4hdb/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/rc4hdb/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/rc4hdb/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/rc4hdb/logic/parser/ParserUtilTest.java
  src/test/java/seedu/rc4hdb/logic/parser/ResidentBookParserTest.java
  src/test/java/seedu/rc4hdb/testutil/ResidentBuilder.java
  src/test/java/seedu/rc4hdb/testutil/ResidentUtil.java
  src/test/java/seedu/rc4hdb/testutil/TypicalIndexes.java
  src/test/java/seedu/rc4hdb/testutil/TypicalPersons.java
  src/test/java/seedu/rc4hdb/testutil/TypicalResidents.java
Labels: priority.High

#66 UI rework
  docs/images/Ui.png
  src/main/java/seedu/rc4hdb/commons/util/FileUtil.java
  src/main/java/seedu/rc4hdb/ui/HelpWindow.java
  src/main/java/seedu/rc4hdb/ui/MainWindow.java
  src/main/java/seedu/rc4hdb/ui/ResidentCard.java
  src/main/java/seedu/rc4hdb/ui/ResidentListPanel.java
  src/main/java/seedu/rc4hdb/ui/ResidentTableView.java
  src/main/java/seedu/rc4hdb/ui/UiManager.java
  src/main/java/seedu/rc4hdb/ui/UiPart.java
  src/main/resources/images/RC4HDB.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResidentListCard.fxml
  src/main/resources/view/ResidentTableView.fxml
Labels: priority.High, type.Chore

#76 Update List command to allow for user to specify fields to list
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/rc4hdb/logic/Logic.java
  src/main/java/seedu/rc4hdb/logic/LogicManager.java
  src/main/java/seedu/rc4hdb/logic/commands/modelcommands/ListCommand.java
  src/main/java/seedu/rc4hdb/logic/parser/ResidentBookParser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/ListCommandParser.java
  src/main/java/seedu/rc4hdb/model/Model.java
  src/main/java/seedu/rc4hdb/model/ModelManager.java
  src/main/java/seedu/rc4hdb/model/resident/fields/Field.java
  src/main/java/seedu/rc4hdb/model/resident/fields/Gender.java
  src/main/java/seedu/rc4hdb/model/resident/fields/House.java
  src/main/java/seedu/rc4hdb/model/resident/fields/MatricNumber.java
  src/main/java/seedu/rc4hdb/model/resident/fields/Name.java
  src/main/java/seedu/rc4hdb/model/resident/fields/Phone.java
  src/main/java/seedu/rc4hdb/model/resident/fields/ResidentFields.java
  src/main/java/seedu/rc4hdb/model/resident/fields/Room.java
  src/main/java/seedu/rc4hdb/model/tag/Tag.java
  src/main/java/seedu/rc4hdb/ui/MainWindow.java
  src/main/java/seedu/rc4hdb/ui/ResidentTableView.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonTableView.fxml
  src/test/java/seedu/rc4hdb/logic/commands/modelcommands/AddCommandTest.java
  src/test/java/seedu/rc4hdb/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/rc4hdb/logic/parser/ResidentBookParserTest.java
Labels: priority.High

#90 Add additional tests and methods in ResidentDescriptorBuilder class
  src/test/java/seedu/rc4hdb/logic/commands/modelcommands/FilterCommandTest.java
  src/test/java/seedu/rc4hdb/testutil/ResidentDescriptorBuilder.java
Labels: priority.High, type.Chore

#71 Updated UG & Test for FindCommand
  docs/UserGuide.md
  src/test/java/seedu/rc4hdb/logic/commands/modelcommands/FindCommandTest.java
  src/test/java/seedu/rc4hdb/model/resident/predicates/NameContainsKeywordsPredicateTest.java
Labels: type.Documentation, priority.High

#103 Update command class
  src/main/java/seedu/rc4hdb/logic/commands/Command.java
  src/main/java/seedu/rc4hdb/logic/commands/misccommands/ExitCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/misccommands/HelpCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/misccommands/MiscCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/modelcommands/AddCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/modelcommands/ClearCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/modelcommands/DeleteCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/modelcommands/EditCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/modelcommands/FilterCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/modelcommands/FindCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/modelcommands/ListCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/modelcommands/ModelCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/storagecommands/StorageCommand.java
Labels: priority.High, type.Chore

#104 Enhance UI
  docs/UserGuide.md
  src/main/java/seedu/rc4hdb/ui/CommandBox.java
  src/main/java/seedu/rc4hdb/ui/HelpWindow.java
  src/main/java/seedu/rc4hdb/ui/MainWindow.java
  src/main/java/seedu/rc4hdb/ui/ResidentTableView.java
  src/main/resources/images/cmd_summary.png
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, type.Enhancement

#110 Groundwork for venue feature
  src/main/java/seedu/rc4hdb/logic/Logic.java
  src/main/java/seedu/rc4hdb/logic/LogicManager.java
  src/main/java/seedu/rc4hdb/model/Model.java
  src/main/java/seedu/rc4hdb/model/ModelManager.java
  src/main/java/seedu/rc4hdb/model/venues/AdHocBooking.java
  src/main/java/seedu/rc4hdb/model/venues/Booking.java
  src/main/java/seedu/rc4hdb/model/venues/RecurrentBooking.java
  src/main/java/seedu/rc4hdb/model/venues/Venue.java
  src/main/java/seedu/rc4hdb/ui/MainWindow.java
  src/main/java/seedu/rc4hdb/ui/VenueTableView.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/VenueTableView.fxml
  src/test/java/seedu/rc4hdb/logic/commands/modelcommands/AddCommandTest.java
  src/test/java/seedu/rc4hdb/model/venues/AdHocBookingTest.java
  src/test/java/seedu/rc4hdb/model/venues/RecurrentBookingTest.java
Labels: type.Story, priority.High

#109 Update Implementation section in DG for Tutorial
  docs/DeveloperGuide.md
  docs/diagrams/plantuml/MainWindowListener.puml
  docs/diagrams/style.puml
  docs/images/ListViewMissingField.png
  docs/images/MainWindowRelationships.png
Labels: type.Documentation, type.Tutorial

#127 Refactor list command into show and hide commands
  src/main/java/seedu/rc4hdb/logic/commands/modelcommands/HideCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/modelcommands/ShowCommand.java
  src/main/java/seedu/rc4hdb/logic/parser/ResidentBookParser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/HideCommandParser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/ShowCommandParser.java
  src/test/java/seedu/rc4hdb/logic/commands/modelcommands/HideCommandTest.java
  src/test/java/seedu/rc4hdb/logic/commands/modelcommands/ShowCommandTest.java
  src/test/java/seedu/rc4hdb/logic/parser/ResidentBookParserTest.java
  src/test/java/seedu/rc4hdb/logic/parser/commandparsers/HideCommandParserTest.java
  src/test/java/seedu/rc4hdb/logic/parser/commandparsers/ShowCommandParserTest.java
Labels: type.Story, priority.High

#111 Adding Specifiers to Filter Command
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/nealetham.md
  src/main/java/seedu/rc4hdb/commons/core/Messages.java
  src/main/java/seedu/rc4hdb/logic/commands/modelcommands/FilterCommand.java
  src/main/java/seedu/rc4hdb/logic/parser/CliSyntax.java
  src/main/java/seedu/rc4hdb/logic/parser/FilterSpecifier.java
  src/main/java/seedu/rc4hdb/logic/parser/ParserUtil.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/FilterCommandParser.java
  src/main/java/seedu/rc4hdb/model/resident/fields/Email.java
  src/main/java/seedu/rc4hdb/model/resident/fields/Gender.java
  src/main/java/seedu/rc4hdb/model/resident/fields/House.java
  src/main/java/seedu/rc4hdb/model/resident/fields/MatricNumber.java
  src/main/java/seedu/rc4hdb/model/resident/fields/Name.java
  src/main/java/seedu/rc4hdb/model/resident/fields/Phone.java
  src/main/java/seedu/rc4hdb/model/resident/fields/Room.java
  src/main/java/seedu/rc4hdb/model/resident/predicates/AttributesMatchAllKeywordsPredicate.java
  src/main/java/seedu/rc4hdb/model/resident/predicates/AttributesMatchAnyKeywordPredicate.java
  src/main/java/seedu/rc4hdb/model/resident/predicates/AttributesMatchKeywordsPredicate.java
  src/main/java/seedu/rc4hdb/model/tag/Tag.java
  src/test/java/seedu/rc4hdb/logic/commands/modelcommands/FilterCommandTest.java
  src/test/java/seedu/rc4hdb/logic/commands/modelcommands/ModelCommandTestUtil.java
  src/test/java/seedu/rc4hdb/logic/parser/ResidentBookParserTest.java
  src/test/java/seedu/rc4hdb/logic/parser/commandparsers/FilterCommandParserTest.java
  src/test/java/seedu/rc4hdb/testutil/TypicalSpecifiers.java
Labels: priority.Moderate, type.Enhancement

#122 Implement Command History
  src/main/java/seedu/rc4hdb/ui/CommandBox.java
  src/main/java/seedu/rc4hdb/ui/history/BackwardHistory.java
  src/main/java/seedu/rc4hdb/ui/history/CommandHistory.java
  src/main/java/seedu/rc4hdb/ui/history/CommandHistoryParser.java
  src/main/java/seedu/rc4hdb/ui/history/ForwardHistory.java
  src/test/java/seedu/rc4hdb/ui/CommandHistoryTest.java
Labels: priority.Low

#131 Add JSON file command abstraction
  src/main/java/seedu/rc4hdb/logic/commands/storagecommands/filecommands/jsonfilecommands/FileCreateCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/storagecommands/filecommands/jsonfilecommands/FileDeleteCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/storagecommands/filecommands/jsonfilecommands/FileSwitchCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/storagecommands/filecommands/jsonfilecommands/JsonFileCommand.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/FileCommandParser.java
  src/test/java/seedu/rc4hdb/logic/LogicManagerTest.java
  src/test/java/seedu/rc4hdb/logic/commands/storagecommands/filecommands/jsonfilecommands/FileCreateCommandTest.java
  src/test/java/seedu/rc4hdb/logic/commands/storagecommands/filecommands/jsonfilecommands/FileDeleteCommandTest.java
  src/test/java/seedu/rc4hdb/logic/commands/storagecommands/filecommands/jsonfilecommands/FileSwitchCommandTest.java
  src/test/java/seedu/rc4hdb/logic/parser/ResidentBookParserTest.java
  src/test/java/seedu/rc4hdb/logic/parser/commandparsers/FileCommandParserTest.java
Labels: priority.High, type.Chore

#134 Implement field class
  src/main/java/seedu/rc4hdb/logic/commands/modelcommands/EditCommand.java
  src/main/java/seedu/rc4hdb/logic/parser/ParserUtil.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/AddCommandParser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/EditCommandParser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/FilterCommandParser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/HideCommandParser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/ListCommandParser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/ShowCommandParser.java
  src/main/java/seedu/rc4hdb/model/Field.java
  src/main/java/seedu/rc4hdb/model/resident/Resident.java
  src/main/java/seedu/rc4hdb/model/resident/ResidentDescriptor.java
  src/main/java/seedu/rc4hdb/model/resident/fields/Email.java
  src/main/java/seedu/rc4hdb/model/resident/fields/Field.java
  src/main/java/seedu/rc4hdb/model/resident/fields/Gender.java
  src/main/java/seedu/rc4hdb/model/resident/fields/House.java
  src/main/java/seedu/rc4hdb/model/resident/fields/MatricNumber.java
  src/main/java/seedu/rc4hdb/model/resident/fields/Name.java
  src/main/java/seedu/rc4hdb/model/resident/fields/Phone.java
  src/main/java/seedu/rc4hdb/model/resident/fields/ResidentField.java
  src/main/java/seedu/rc4hdb/model/resident/fields/ResidentFields.java
  src/main/java/seedu/rc4hdb/model/resident/fields/Room.java
  src/main/java/seedu/rc4hdb/model/resident/fields/Tag.java
  src/main/java/seedu/rc4hdb/model/resident/predicates/AttributesMatchAllKeywordsPredicate.java
  src/main/java/seedu/rc4hdb/model/resident/predicates/AttributesMatchAnyKeywordPredicate.java
  src/main/java/seedu/rc4hdb/model/resident/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/rc4hdb/model/util/SampleDataUtil.java
  src/main/java/seedu/rc4hdb/storage/JsonAdaptedResident.java
  src/main/java/seedu/rc4hdb/storage/JsonAdaptedTag.java
  src/main/java/seedu/rc4hdb/ui/ResidentTableView.java
  src/test/java/seedu/rc4hdb/logic/commands/modelcommands/ModelCommandTestUtil.java
  src/test/java/seedu/rc4hdb/logic/parser/ParserUtilTest.java
  src/test/java/seedu/rc4hdb/logic/parser/commandparsers/AddCommandParserTest.java
  src/test/java/seedu/rc4hdb/logic/parser/commandparsers/EditCommandParserTest.java
  src/test/java/seedu/rc4hdb/logic/parser/commandparsers/FilterCommandParserTest.java
  src/test/java/seedu/rc4hdb/logic/parser/commandparsers/HideCommandParserTest.java
  src/test/java/seedu/rc4hdb/logic/parser/commandparsers/ListCommandParserTest.java
  src/test/java/seedu/rc4hdb/logic/parser/commandparsers/ShowCommandParserTest.java
  src/test/java/seedu/rc4hdb/model/ModelManagerTest.java
  src/test/java/seedu/rc4hdb/model/resident/fields/TagTest.java
  src/test/java/seedu/rc4hdb/testutil/ResidentBuilder.java
  src/test/java/seedu/rc4hdb/testutil/ResidentDescriptorBuilder.java
  src/test/java/seedu/rc4hdb/testutil/ResidentUtil.java
Labels: priority.Low, type.Chore

#141 Fix table UI tag bug
  src/main/java/seedu/rc4hdb/ui/ResidentTableView.java
Labels: type.Bug, severity.Low

#133 Implement Import Command
  src/main/java/seedu/rc4hdb/commons/exceptions/DataConversionException.java
  src/main/java/seedu/rc4hdb/logic/commands/storagecommands/filecommands/csvfilecommands/CsvFileCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/storagecommands/filecommands/csvfilecommands/ImportCommand.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/FileCommandParser.java
  src/main/java/seedu/rc4hdb/storage/Storage.java
  src/main/java/seedu/rc4hdb/storage/StorageManager.java
  src/main/java/seedu/rc4hdb/storage/csv/CsvFileManager.java
  src/main/java/seedu/rc4hdb/storage/csv/CsvReader.java
  src/main/java/seedu/rc4hdb/storage/csv/exceptions/InvalidCsvFileFormatException.java
  src/test/data/CsvReaderTest/invalidCsvFormat.csv
  src/test/data/CsvReaderTest/invalidEmail.csv
  src/test/data/CsvReaderTest/invalidGender.csv
  src/test/data/CsvReaderTest/invalidHouse.csv
  src/test/data/CsvReaderTest/invalidMatricNumber.csv
  src/test/data/CsvReaderTest/invalidName.csv
  src/test/data/CsvReaderTest/invalidPhone.csv
  src/test/data/CsvReaderTest/invalidRoom.csv
  src/test/data/CsvReaderTest/invalidTags.csv
  src/test/data/CsvReaderTest/tooManyCommas.csv
  src/test/data/CsvReaderTest/validCsvWithBom.csv
  src/test/data/CsvReaderTest/validMultiResident.csv
  src/test/data/CsvReaderTest/validMultiTag.csv
  src/test/data/CsvReaderTest/validSingleRow.csv
  src/test/java/seedu/rc4hdb/commons/exceptions/DataConversionExceptionTest.java
  src/test/java/seedu/rc4hdb/logic/StorageStub.java
  src/test/java/seedu/rc4hdb/logic/commands/storagecommands/StorageCommandTestUtil.java
  src/test/java/seedu/rc4hdb/logic/commands/storagecommands/filecommands/csvfilecommands/ImportCommandTest.java
  src/test/java/seedu/rc4hdb/logic/parser/commandparsers/FileCommandParserTest.java
  src/test/java/seedu/rc4hdb/storage/StorageManagerTest.java
  src/test/java/seedu/rc4hdb/storage/csv/CsvFileManagerTest.java
  src/test/java/seedu/rc4hdb/storage/csv/CsvReaderTest.java
Labels: type.Story, priority.High

#182 Add SampleData
  src/main/java/seedu/rc4hdb/model/util/SampleDataUtil.java
Labels: priority.High

#187 Update DG v1.3
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
Labels: type.Documentation, priority.High

#192 UI update
  docs/images/UI.png
  docs/images/Ui.png
  docs/images/venue_tab_ui.png
  src/main/java/seedu/rc4hdb/logic/Logic.java
  src/main/java/seedu/rc4hdb/logic/LogicManager.java
  src/main/java/seedu/rc4hdb/model/Model.java
  src/main/java/seedu/rc4hdb/model/ModelManager.java
  src/main/java/seedu/rc4hdb/model/venues/DailySchedule.java
  src/main/java/seedu/rc4hdb/ui/BookingTableView.java
  src/main/java/seedu/rc4hdb/ui/MainWindow.java
  src/main/java/seedu/rc4hdb/ui/VenueListCard.java
  src/main/java/seedu/rc4hdb/ui/VenueListView.java
  src/main/java/seedu/rc4hdb/ui/VenueTabView.java
  src/main/resources/view/BookingTableView.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResidentTableView.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/VenueListCard.fxml
  src/main/resources/view/VenueListView.fxml
  src/main/resources/view/VenueTabView.fxml
  src/test/java/seedu/rc4hdb/model/ModelStub.java
Labels: priority.Moderate, type.Enhancement

#197 Fix erroneous success message when calling list
  src/main/java/seedu/rc4hdb/logic/commands/residentcommands/ColumnManipulatorCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/residentcommands/HideOnlyCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/residentcommands/ListCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/residentcommands/ResetCommand.java
  src/main/java/seedu/rc4hdb/logic/commands/residentcommands/ShowOnlyCommand.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/ColumnManipulatorCommandParser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/HideOnlyCommandParser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/ListCommandParser.java
  src/main/java/seedu/rc4hdb/logic/parser/commandparsers/ShowOnlyCommandParser.java
  src/main/java/seedu/rc4hdb/ui/MainWindow.java
  src/main/java/seedu/rc4hdb/ui/ResidentTableView.java
  src/test/java/seedu/rc4hdb/logic/LogicManagerTest.java
  src/test/java/seedu/rc4hdb/logic/commands/residentcommands/ListCommandTest.java
  src/test/java/seedu/rc4hdb/logic/parser/Rc4hdbParserTest.java
  src/test/java/seedu/rc4hdb/logic/parser/commandparsers/ListCommandParserTest.java
Labels: type.Bug, severity.Low

#132 UG reorganization
  docs/DeveloperGuide.md
  docs/FileCommands.md
  docs/FileCreateCommand.md
  docs/FileDeleteCommand.md
  docs/FileSwitchCommand.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/ug-photos/filter_command.png
  docs/images/ug-photos/filter_command_2.png
  docs/images/ug-photos/find_command.png
  docs/images/ug-photos/list_command.png
  docs/images/ug-photos/list_i_list_e_command.png
  docs/images/ug-photos/showonly_command.png
  docs/team/nealetham.md
  docs/ug-pages/authors.md
  docs/ug-pages/command-summary.md
  docs/ug-pages/data-management.md
  docs/ug-pages/exiting-the-program.md
  docs/ug-pages/faq.md
  docs/ug-pages/file-management.md
  docs/ug-pages/getting-help.md
  docs/ug-pages/glossary.md
  docs/ug-pages/modifying-residents.md
  docs/ug-pages/quality-of-life.md
  docs/ug-pages/upcoming-features.md
  docs/ug-pages/venue-booking.md
  docs/ug-pages/viewing-residents.md
Labels: type.Documentation, priority.High

#201 Add unit tests for storage component
  src/main/java/seedu/rc4hdb/storage/StorageManager.java
  src/main/java/seedu/rc4hdb/storage/residentbook/JsonAdaptedTag.java
  src/main/java/seedu/rc4hdb/storage/venuebook/JsonAdaptedRecurrentBooking.java
  src/test/data/JsonSerializableVenueBookTest/duplicateVenueVenueBook.json
  src/test/data/JsonSerializableVenueBookTest/invalidVenueVenueBook.json
  src/test/data/JsonSerializableVenueBookTest/typicalVenuesVenueBook.json
  src/test/data/JsonVenueBookStorageTest/invalidAndValidVenueVenueBook/venue_data.json
  src/test/data/JsonVenueBookStorageTest/invalidVenueVenueBook/venue_data.json
  src/test/data/JsonVenueBookStorageTest/notJsonFormatVenueBook/venue_data.json
  src/test/java/seedu/rc4hdb/storage/DataStorageManagerTest.java
  src/test/java/seedu/rc4hdb/storage/StorageManagerTest.java
  src/test/java/seedu/rc4hdb/storage/venue/JsonAdaptedRecurrentBookingTest.java
  src/test/java/seedu/rc4hdb/storage/venue/JsonAdaptedVenueTest.java
  src/test/java/seedu/rc4hdb/storage/venue/JsonSerializableVenueBookTest.java
  src/test/java/seedu/rc4hdb/storage/venue/JsonVenueBookStorageTest.java
  src/test/java/seedu/rc4hdb/testutil/TypicalVenues.java
  src/test/java/seedu/rc4hdb/ui/CommandHistoryTest.java
Labels: priority.High

#262 Update UG and DG
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/plantuml/ColorCoding.puml
  docs/images/ColorCoding.png
  docs/images/LatestModelClassDiagram.png
  docs/ug-pages/faq.md
  docs/ug-pages/viewing-residents.md
Labels: type.Documentation, priority.High
